name: idealize_new_version
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.1.0+2

environment:
  sdk: '>=3.2.3 <4.0.0'

  
dependencies:
  flutter:
    sdk: flutter

  intl: ^0.19.0  
  cupertino_icons: ^1.0.2
  http: ^1.1.2
  get: ^4.6.6
  gap: ^3.0.1
  flutter_svg: ^2.0.9
  overlay_support: ^2.1.0
  image_picker: ^1.0.7
  dotted_border: ^2.1.0
  http_parser: ^4.0.2
  path: ^1.8.0
  path_provider: ^2.0.2
  url_launcher: ^6.2.5
  file_picker: ^8.0.0+1
  flutter_image_compress: ^2.2.0
  flutter_secure_storage: ^9.0.0
  get_storage: ^2.1.1
  loader_overlay: ^4.0.0
  cached_memory_image: ^1.5.0
  socket_io_client: ^3.0.0
  adaptive_dialog: ^2.3.0
  permission_handler: ^11.3.1
  cached_network_image: ^3.4.1
  modal_bottom_sheet: ^3.0.0
  pin_code_fields: ^8.0.1
  dio: ^5.8.0+1
  open_filex: ^4.7.0


get:
  flutter_localizations:
    sdk: flutter
  intl: any



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.14.3 # flutter pub run flutter_launcher_icons

flutter_icons:
  android: true
  ios: true
  image_path: "assets/png/app_logo_staging.png"
  adaptive_icon_background: "#2F3C72"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/png/
    - assets/svg/
    - assets/fonts/
  

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: iconsax
      fonts:
        - asset: assets/fonts/iconsax.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
